### PR TITLE
bump next-transpile-modules

### PR DESCRIPTION
**Pull request by DevonD123**
updated to v10 to fix issue with dev build
image

### CODE REVIEW

**Comment by avitorio** [comment]
Thanks for the PR! I'll review it asap.

**Comment by avitorio** [comment]
I am unable to reproduce the issue, my concern is that this bump may not be backwards compatible for people using Next.js 12. What error did you exactly get? Can you specify the steps to reproduce it? Thanks.

**Comment by avitorio** [comment]
Hey @DevonD123, I'm closing the pull request because it seems you were committing other work to it.

**Comment by DevonD123** [comment]
good call, my bad should have done those in a branch. anyways this seems to not be an issue on my device anymore, I think i may have initially ran an npm i instead on pnpm to get the error

**Pull request closed without merging**
