### PR TITLE
Added a checker function to see if the user is a collaborator

### PR DESCRIPTION
**Pull request by ZiyadBoshima**
This was done to prevent users who are not collaborators in the repo to sign in to the dashboard.

REQUIREMENTS:

OST_REPO_OWNER has to be set to a value in order for the api request to be valid. Therefore, with this code, it is no longer an optional environmental variable.

## Feature

- [x] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Integration tests added

### CODE REVIEW

**Comment by avitorio** [comment]
Hey @ZiyadBoshima, this looks great!

I have removed some files that were not needed for the PR (pnpm-lock, and next-env.d.ts).
I've also added the Alert component and a new way to pass down error messages from the login section.

I think a good addition to this PR would be to also check if the repository exists. If not, return a 'repository-not-found' error linking users to check their environment variables at `https://outstatic.com/docs/environment-variables` .

**Comment by avitorio** [comment]
I've also added a check to see if `OST_REPO_OWNER` is set, and only run `isCollaborator()` in case the user has that env var setup. Outstatic assumes your Github username is the OST_REPO_OWNER when that variable isn't set up, that's why it's optional.

I don't want to make the `OST_REPO_OWNER` a required env var.

That's why checking if the repo exists is a good second step. Because if you own the repository, then you are a collaborator by default.

**Comment by ZiyadBoshima** [comment]
Hey, I am glad the initial code was useful in some way. Also, it makes sense to me now why you don't want the repo owner env variable required. 

I will add the feature to check if the repo exists soon.

**Review by avitorio — APPROVED** [review]
Hey @ZiyadBoshima, I'm going to merge this PR.
Thanks for your help. If you want to create the check to see if the repo exists, please create a new PR.

**Pull request merged**
