### PR TITLE
chore: Adds Husky/Lint checks for incoming files

### LINKED ISSUE #63: Hsuky / Prettier Support
Following [this discussion](https://github.com/avitorio/outstatic/discussions/54#discussioncomment-4107145), we'll be moving on with enforcing code styles and formatting on commit. 

This solution may not be final but it's better than nothing. We can always improve on it on future releases.

Thank you @DCzajkowski for kicking off the discussion and @jakobo for actively participating on it.

### PR DESCRIPTION
**Pull request by jakobo**
Updates the code to run prettier & eslint --fix on commit. After the discussion in #54, the goal was to get some basic code quality infrastructure in as close to the developer as possible to shorten the code->feedback loop. This does not change existing files, only files staged for commit.

Resolves #63

### CODE REVIEW

**Review by avitorio — APPROVED** [review]
Excellent! Husky blocked me from commiting an ugly file 🤣

**Review by avitorio — APPROVED** [review]

**Comment by DCzajkowski** [comment]
@jakobo I've just commited 8 files locally, that were already prettified. The commit took 5.572s. On the second attempt of the same commit, 3.188s.

Additionally, it prohibited me from committing from within GitHub Desktop (see the screenshot below).

Screen Shot 2022-11-20 at 9 43 57 PM

I don't think this constitutes a good DX :/

**Comment by jakobo** [comment]
I’ll look into that, it is likely just an error in how the husky call to
lint-staged is setup.

WRT timing, I’ll see what’s causing the issue. My guess is that it’s the
eslint checks, but running `time` against the individual commands can help
triage.

**Comment by jakobo** [comment]
>Additionally, it prohibited me from committing from within GitHub Desktop (see the screenshot below).

Opened #69 with the fixes for github desktop. Specifically
* Color ascii codes are dropped, no more FORCE_COLOR
* older --shell arg isn't required. We could rewrite the script as `pnpm run lint-staged -- --shell` but nothing we're currently doing in our lint-staged file benefits from non-parsed shell scripting.

**Comment by jakobo** [comment]
I ran this patch against #67, as that's a good representation of workflow. It's 8 files, and we're asking prettier & eslint to write to the filesystem if there are problems. Timing Information included first. In all situations, I took the worst run over 7 samples. Tests performed via WSL `4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

## Raw lint-staged

Ran with no commands (pure lint-staged hook). The 0.65s is likely the shell command to git to (A) stash and (B) request the changeset
```
$ time pnpm run lint-staged

> @ lint-staged /home/jakobo/code/outstatic
> lint-staged

✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
pnpm run lint-staged  0.65s user 0.12s system 132% cpu 0.584 total
```

## eslint --fix

Ran with only `eslint --fix`. This shells out to eslint, and its safe to say anything beyond the 0.65 is overhead of running eslint. It represents **1.28 seconds** to check 8 files using our eslint custom ruleset which includes
* next.js checks
* turbo checks
* a redundant prettier check (to remove)

Removing the redundant prettier check saved `0.1` over 7 test runs.
```
$ time pnpm run lint-staged

> @ lint-staged /home/jakobo/code/outstatic
> lint-staged

✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
pnpm run lint-staged  1.93s user 0.36s system 128% cpu 1.777 total
```

## prettier --write

Ran with only `prettier --write`. The overhead seems comparable to eslint, which makes me think the lint-staged check will be linear relative to the number of files checked. This can be confirmed by running both together.
```
$ time pnpm run lint-staged

> @ lint-staged /home/jakobo/code/outstatic
> lint-staged

✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
pnpm run lint-staged  1.53s user 0.17s system 129% cpu 1.323 total
```

Ran with both `eslint --fix` and `prettier --write`. With **2.8s** this would track that the most expensive operation is shelling out to every eslint command. lint-staged operates by calling `eslint --fix [files]` & `prettier --write [files]` which would increase linearly with the number of files checked.

```
$ time pnpm run lint-staged

> @ lint-staged /home/jakobo/code/outstatic
> lint-staged

✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
pnpm run lint-staged  2.80s user 0.27s system 128% cpu 2.392 total
```

## Thoughts

The cost per file is ~0.25s per file checked. If people are keeping their commits small, there should not be significant slowdown. However, if a change includes a large set of files (15-20 files) it's reasonable to expect that a formatting pass will take a few moments. I empathize with both yours and Theo's concerns about interfering with someone's workflow. However, because we have several contributors, we need to ensure a minimum code quality in

* Merges
* Pull Requests

Creating thrash on PRs through multiple fixup commits & force-pushes makes it harder for code reviewers to look through a changeset. I contribute to projects with both approaches, and those that check code before push are significantly more enjoyable to work with. I agree with you that Outstatic needs a good DX for contributors. I also believe that it can't come at additional burden to maintainers. We're all doing this in our spare time out of a love for what Outstatic can become.

I'm always happy to talk more about this in the discord.

**Pull request merged**
