### PR TITLE
chore: Doc for local development

### PR DESCRIPTION
**Pull request by leplay**
## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [x] Documentation added

----

When I tried to run Outstatic locally, it took me some time to get it to work. I hope this documentation is helpful for new users.

### CODE REVIEW

**Comment by avitorio** [comment]
This is excellent, thanks! We need to add a link to this page after the "deploy to vercel" section in the Getting Started guide. Can you try to find a nice place for it?

**Comment by leplay** [comment]
Happy to do it.

**Comment by avitorio** [comment]
Hey @leplay,

The build is failing. You need to run **Rebuild Metadata** since this doc wasn't created using Outstatic.

Go to your Outstatic Dashboard > Settings > Rebuild Metadata

Once that's done I'll approve the PR. Thanks!

**Review by avitorio — APPROVED** [review]
LGTM

**Pull request merged**
